services:
  app:
    build:
      dockerfile: Dockerfile
    env_file:
      - .env
    depends_on:
      - migrate
    ports:
      - "$PORT:$PORT"

  postgres:
    image: postgres:alpine
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 10s
      retries: 3
      start_period: 7s
      timeout: 10s
    env_file:
      - .env
    ports:
      - "5432:5432"

  migrate:
    image: migrate/migrate
    env_file:
      - .env
    volumes:
      - ./migrations:/migrations
    depends_on:
      postgres:
        condition: service_healthy
    command: ["-path", "/migrations", "-database",  "postgres://$POSTGRES_USER:$POSTGRES_PASSWORD@postgres:5432/$POSTGRES_DB?sslmode=disable", "up"]